spring:
  datasource:
    url: jdbc:mysql://8.130.122.134:3306/gym
    username: root
    password: 200136Lyf.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
server:
  port: 15666
  url_prefix: http://localhost:15666/file/get
  base_path: E:\Code\Java\gym_manager_web\workpalce